cas.server-url-prefix : http://10.55.8.28:30080/cas
cas.server-login-url :  http://10.55.8.28:30080/cas/login
cas.client-host-url : http://10.29.133.108:8004
cas.use-session : true
cas.validation-type : CAS
server:
  port: 8004
  #配置添加
xtpUrl: http://10.29.135.113:8181/reconmendSys/report/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:logback-prod.xml
com:
  zhongtai:
    name : "ren"
    want : "zedong"
    webOriginHref : http://10.29.133.108:8006
    mobileOriginHref : http://10.25.26.187:8080