cas.server-url-prefix : http://10.29.181.202:30080/cas
cas.server-login-url : http://10.29.181.202:30080/cas/login
cas.client-host-url : http://10.25.26.187:8004
cas.use-session : true
cas.validation-type : CAS
com:
  zhongtai:
    name : "ren"
    want : "zedong"
    webOriginHref :  http://10.25.26.187:4000
    mobileOriginHref : http://10.25.26.187:8080
    ignoreHostUrl: /mobileUrl/*
udf:
  ignore-host-url: http://10.25.26.187:8004/mobileUrl/
  ignore-url-pattern-type: ""