
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8004
#  servlet:
#   context-path : /api
#配置添加
xtpUrl : http://10.25.102.194:8080/reconmendSys/report/
logging:
  config: classpath:logback-dev.xml
spring.mvc.static-path-pattern : /**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/